config/routes.rb
Rails.application.routes.draw do
  root 'user_sessions#new'

  resources :user_sessions
  resources :users do
    resources :entries
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get '/portfolio' => 'user_sessions#portnew'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user

  validates :event, presence: true
  validates :date, presence: true
  validates :longitude, presence: true
  validates :latitude, presence: true
  validates :weather, presence: true
  validates :weather_img, presence: true
  validates :emotion, presence: true
  validates :description, presence: true


  def self.data_to_array(params)
    @colors = []
    @user = User.find(params[:user_id])

    # logs total number of hits for an emotion... saved for future feature
    # @silvers = @user.entries.where(emotion_num:"0").count('date', :distinct => true)
    # @reds = @user.entries.where(emotion_num:"1").count('date', :distinct => true)
    # @oranges = @user.entries.where(emotion_num:"2").count('date', :distinct => true)
    # @yellows = @user.entries.where(emotion_num:"3").count('date', :distinct => true)
    # @greens = @user.entries.where(emotion_num:"4").count('date', :distinct => true)
    # @blues = @user.entries.where(emotion_num:"5").count('date', :distinct => true)
    # @purples = @user.entries.where(emotion_num:"6").count('date', :distinct => true)
    # @colors.push(@silvers, @reds, @oranges, @yellows, @greens, @blues, @purples)

    previous_dates = []
    @user.entries.select(:date).uniq.limit(7).each do |entry|
      previous_dates.push(entry.date)
    end

    dates = previous_dates.sort!

    guide_line = [
    ['0%', '#808080'],
    ['15%', '#FF0000'],
    ['30%', '#FFA500'],
    ['45%', '#FFFF00'],
    ['60%', '#00FF00'],
    ['75%', '#0000FF'],
    ['90%', '#4B0082']]

    @data = []
    date_arr = []

    # for data in dates
    dates.each do |date|
      @user.entries.where(date:date).each do |entry|
        if entry.emotion_num =="0"
          date_arr.push(guide_line[0])
        elsif entry.emotion_num =="1"
          date_arr.push(guide_line[1])
        elsif entry.emotion_num =="2"
          date_arr.push(guide_line[2])
        elsif entry.emotion_num =="3"
          date_arr.push(guide_line[3])
        elsif entry.emotion_num =="4"
          date_arr.push(guide_line[4])
        elsif entry.emotion_num =="5"
          date_arr.push(guide_line[5])
        else entry.emotion_num =="6"
          date_arr.push(guide_line[6])
        end
      end
      date_arr.sort!
      @data.push(date_arr)
      date_arr = []
    end
    return @data
  end

  def self.color_key
    color_guide_line = [
    ['Neutral', 'rgba(0,0,0,0.2)'],
    ['Angry', 'rgba(255,0,0,0.8)'],
    ['Afraid', 'rgba(255,201,0,0.8)'],
    ['Surprised', 'rgba(255,255,0,0.8)'],
    ['Happy', 'rgba(0,255,0,0.8)'],
    ['Sad', 'rgba(0,0,255,0.6)'],
    ['Disgusted', 'rgba(75,0,150,0.7)']]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :entries
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :require_login
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @entries = User.find(params[:user_id]).entries.order('created_at DESC').limit(6)
    @data = Entry.data_to_array(params)
    @color_key = Entry.color_key
    respond_to do |f|
      f.html
      f.json {render json: @entries}
    end
  end


  def show
    @entry = Entry.find(params[:id])
    redirect_to entries_user_path(@user.id)
  end

  def new
    @user = User.find(session[:user_id])
    @entry = Entry.new
  end

  def create
    entry = Entry.create(entry_params)
    redirect_to user_entries_path
  end

  def show
    @user = User.find(params[:user_id])
    @entry = Entry.find(params[:id])
  end

  def edit
    entry = User.find(params[:user_id]).entries.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def update
    edited_entry = User.find(params[:user_id]).entries.find(params[:id])
    edited_entry.update(entry_params)
    redirect_to "/users/#{user.id}/entries"
  end

  def destroy
    @entry = User.find(params[:user_id]).entries.find(params[:id])
    @entry.delete
    redirect_to user_entries_path
  end
  private
  def entry_params
    params.require(:entry).permit(:user_id, :date, :event, :emotion, :emotion_num, :longitude, :latitude, :weather, :weather_img, :description)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]

  def index
    redirect_to login_path
  end

  def new
    @user = User.new
  end

  def show
    redirect_to user_entries_path
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to user_path(@user.id), notice: 'Login successful'
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'Logged out!')
  end

  def portnew
    #controller for example login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:index, :new, :create]

  def index
  end

  def show
    redirect_to users_path
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to :login, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/_form.html.erb
<%= form_for @entry do |f| %>
  <%= f.label :event %>
  <%= f.text_field :event %>
  <%= f.label :description %>
  <%= f.text_field :descriptionn %>
  <%= f.submit %>
<% end %>

app/views/entries/edit.html.erb
<div class="container">

    <div class="two-third column color-box fadeable">
    </div>
    <div class="one-third column weather-box fadeable">
      <div style="height: 300px;" id="weather-info">
      </div>
    </div>
    <div class="sixteen columns form-box fadeable">
      <form id="entry-log" action="/users/<%= @user.id %>/entries" method="post">
        <input type='hidden' name='_method' value='put'>
        <%= token_tag %>
          <input type='hidden' name="entry[date]" data-name="date">
          <input type='hidden' name="entry[longitude]" data-name="lon">
          <input type='hidden' name="entry[latitude]" data-name="lat">
          <input type='hidden' name="entry[user_id]" value="<%= @user.id%>">
          <input type='hidden' name="entry[emotion_num]" id="emo_num">
          Event:<input type="text" name="entry[event]">
          <input id="color-to-emotion" type="hidden" name="entry[emotion]">
          <input type="hidden" name="entry[weather]" data-name="weather">
          <input type="hidden" name="entry[weather_img]" data-name="weather_con">
          Description:<textarea name="entry[description]" rows="5" cols="50" form="entry-log"></textarea>
          <input type="submit" value="Edit Entry">
      </form>

    </div>
    <div class="sixteen columns map-box">
    </div>

  </div>
</div>

app/views/entries/index.html.erb
<%= javascript_tag "var entries = #{@entries.to_json};
                    var data = #{@data};  " %>

<script>
  setTimeout(function(){
    projectData();
    updateAll(data);
  }, 2000);
</script>


<div class="container fadeable">
  <div class="sixteen columns">
    <div class="x-scrollable" id="emotion-wheel">
      <h3>Emotional gradient over the last <%= @data.count %> days...</h3>
      <div id="color-key">
        <table>
          <tbody>
            <tr>
              <td> Emotion-color Key: </td>
            </tr>
            <% @color_key.each do |key| %>
            <tr>
              <td style="background: <%= key[1] %>">
                <%= key[0] %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="svg-container x-scrollable">
        <svg>
          <g>
            <defs>
              <linearGradient id="myGradient0">
              </linearGradient>
              <linearGradient id="myGradient1">
              </linearGradient>
              <linearGradient id="myGradient2">
              </linearGradient>
              <linearGradient id="myGradient3">
              </linearGradient>
              <linearGradient id="myGradient4">
              </linearGradient>
              <linearGradient id="myGradient5">
              </linearGradient>
              <linearGradient id="myGradient6">
              </linearGradient>
            </defs>
          </g>
        </svg>
      </div>
    </div>
  </div>
  <div class="clearfix">
    <h3> Six most recent Entries:</h3>
    <% @entries.each do |entry| %>
      <a href="/users/<%= @user.id %>/entries/<%= entry.id %>">
        <div class="entry-display <%= entry.emotion.downcase %>">
          <ul>
            <li><strong>Date</strong>: <%= entry.date %></li>
            <li><strong>Event</strong>: <%= entry.event %></li>
            <li><strong>Feeling</strong>: <%= entry.emotion %></li>
            <li><strong>Temperature</strong>: <%= entry.weather %></li>
            <li><strong>Conditions</strong>: <%= entry.weather_img %></li>
            <li><strong>Description</strong>: <%= entry.description %></li>
          </ul>
        </div>
      </a>
    <% end %>
  </div>
</div>

app/views/entries/new.html.erb
<div class="container fadeable">

    <div class="one-third column color-box">
      <h3>How are you feeling?</h3>
      <p>
        Please choose a color from the wheel.
      </p>
      <form name="new-entry" id="entry-log" action="/users/<%= @user.id %>/entries" onsubmit="return validateForm()" method="post">
        <%= token_tag %>
        <input style="width:100%" class="centerable" id="color-to-emotion" type="text" name="entry[emotion]" placeholder="I feel..">
    </div>
    <div class="one-third column weather-box">
      <div style="height: 300px;" id="weather-info">
        <h3>Today's conditions</h3>
        <p> weather and location will be added automatically</p>
          longitude:<input type='text' name="entry[longitude]" data-name="lon">
          latitude:<input type='text' name="entry[latitude]" data-name="lat">
      </div>
    </div>
    <div class="one-third column form-box">
      <h3>Write a little something...</h3>
      <p>please fill in the missing pieces...</p>
        <input type='hidden' name="entry[date]" data-name="date">
        <input type='hidden' name="entry[longitude]" data-name="lon">
        <input type='hidden' name="entry[latitude]" data-name="lat">
        <input type='hidden' name="entry[user_id]" value="<%= @user.id%>">
        <input type='hidden' name="entry[emotion_num]" id="emo_num">
        <input type="hidden" name="entry[weather]" data-name="weather">
        <input type="hidden" name="entry[weather_img]" data-name="weather_con">
        Event:<input type="text" name="entry[event]">
        Description:<textarea name="entry[description]" rows="5" cols="50" form="entry-log"></textarea>
        <input type="submit" value="Add Entry">
      </form>

    </div>
    <div class="sixteen columns map-box">
    </div>

  </div>
</div>

app/views/entries/show.html.erb
<div class="container">

  <div class="entry-display <%= @entry.emotion.downcase %> single-entry">
    <ul>
      <li>Event: <%= @entry.event %></li>
      <li>When: <%= @entry.date %></li>
      <li>Feeling: <%= @entry.emotion %></li>
      <li>Longitude: <%= @entry.longitude %></li>
      <li>Latitude: <%= @entry.latitude %></li>
      <li>Temperature: <%= @entry.weather %></li>
      <li>Conditions: <%= @entry.weather_img %></li>
      <li>Description: <%= @entry.description %></li>
      <form action="/users/<%= @user.id %>/entries/<%= @entry.id %>" method="post">
        <input type='hidden' name="_method" value="delete">
        <%= token_tag %>
        <input type='submit' value='Delete Entry'>
      </form>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>PersonalityPalette</title>
  <link href='http://fonts.googleapis.com/css?family=Hind:400,300' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=320; initial-scale=1.0; maximum-scale=2.0; user-scalable=2;"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body class="<%= controller_name %>">

  <div id="nav">
    <div class="container">

        <h2 class="six columns">
          <i>Personality Palette</i>
          <%= image_tag "logo.png", :class => "site-logo add-bottom" %>
        </h2>
        <ul class="six columns nav-bar">
        <% if current_user %>
          <li><%= link_to "Home", user_path(current_user), method: :get %></li>
          <li><%= link_to "New Entry", new_user_entry_path(current_user), method: :get %></li>
          <li><%= link_to "View All", user_entries_path(current_user), method: :get %></li>
          <li><%= link_to "Logout", logout_path, method: :post %></li>
        <% else %>
            <li><%= link_to "Register", new_user_path %></li>
            <li><%= link_to "Login", :login %></li>
        <% end %>
        </ul>
    </div>
  </div>

  <div id="flash">
    <div class="container">
      <div class="sixteen columns">
        <% if current_user %>
          <p class="session-log" id="notice"><%= flash[:notice] %></p>
        <% else %>
          <p class="session-log" id="notice"><%= flash[:notice] %></p>
          <p class="session-log" id="alert"><%= flash[:alert] %></p>
        <% end %>
      </div>
    </div>
  </div>

 <%= yield %>

</body>
</html>

app/views/user_sessions/_form.html.erb
<div class="offset-by-five">
  <%= form_tag user_sessions_path, :id => 'log-window', :class => 'six columns', :method => :post do %>
    <div class="field">
      <%= label_tag :email %>
      <%= text_field_tag :email %>
    </div>
    <div class="field">
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </div>
    <div class="actions">
      <%= submit_tag "Login" %>
      <%= link_to "Register", new_user_path, :class => "button centerable", :method => :get %>
    </div>
  <% end %>
</div>

app/views/user_sessions/_loggedin.html.erb
<div class="offset-by-five">
  <%= form_tag user_sessions_path, :id => 'log-window', :class => 'six columns', :method => :post do %>
    <div class="field">
      <%= label_tag :email %>
      <%= text_field_tag('email', 'ntuvera@gmail.com') %>
    </div>
    <div class="field">
      <%= label_tag :password %>
      <%= password_field_tag('password', 'password') %>
    </div>
    <div class="actions">
      <%= submit_tag "Login" %>
      <%= link_to "Register", new_user_path, :class => "button centerable", :method => :get %>
    </div>
  <% end %>
</div>

app/views/user_sessions/new.html.erb
<div class="container">

    <%= render 'form' %>

</div>

app/views/user_sessions/portnew.html.erb
<div class="container">

    <%= render 'loggedin' %>

</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :id => 'log-window', :class => 'six columns' } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this@user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
     <%= f.label :password %>
     <%= f.password_field :password %>
  </div>
  <div class="field">
     <%= f.label :password_confirmation %>
     <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="sixteen columns fadeable">

    <blockquote>sometimes a picture is worth a thousand words...</blockquote>
    <h2>Personality Palette...</h2>
    <p> is a simple journal-based system that maps felt emotions between entries. Currently, it supports your current emotion palette over the last week, but future implementation will allow you to view up to the last 30 to 90 days.   </p>

    <h4>To get started...</h4>
    <p> click the new Entry button.  You can then select a color to represent link an emotion to the post, and fill in some details about how you're feeling.  You must log an event, emotion and a small description; the location and weather conditions will also be logged for future data visualization.</p>
    <p>We recommend that you create at least two entries per a day to get a more robust visualization, but it's completely up to you.  Whenever you feel something, leave an entry.  You can look back at how you've felt and why to get a better understanding of yourself and the events that affect you.</p>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="offset-by-five">

    <%= render 'form' %>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="sixteen columns fadeable">

    <blockquote>sometimes a picture is worth a thousand words...</blockquote>
    <h2>Personality Palette...</h2>
    <p> is a simple journal-based system that maps felt emotions between entries. Currently, it supports your current emotion palette over the last week, but future implementation will allow you to view up to the last 30 to 90 days.   </p>

    <h4>To get started...</h4>
    <p> click the new Entry button.  You can then select a color to represent link an emotion to the post, and fill in some details about how you're feeling.  You must log an event, emotion and a small description; the location and weather conditions will also be logged for future data visualization.</p>
    <p>We recommend that you create atleast two entries per a day to get a more robust visualization, but it's completely up to you.  Whenever you feel something, leave an entry.  You can look back at how you've felt and why to get a better understanding of yourself and the events that affect you.</p>
  </div>
</div>